version: "3.8"

services:
  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "testapp"
      MYSQL_USER: "rizky"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3308:3306"